### ISSUE TITLE
Shop is being cut off on sticky header so only displaying op

### ISSUE THREAD

**Issue by mandi920** [tastefully-simple/cornerstone#358] opened 2020-10-06 15:25 UTC
### Expected behavior
I would expect to see the whole word shop when I scroll through the page making the sticky header appear

### Actual behavior
The word shop is being cut off so it is only displaying op

### Steps to reproduce behavior
On an ipad scroll down on the page to get the sticky header to appear.

**Comment by jsmnglng-w** [comment] 2020-10-06 18:55
Ticket for this issue: [TST-233](https://razoyo.atlassian.net/browse/TST-233)

**Comment by monicakarnes** [comment] 2020-10-13 14:20
Not sure what Ipad the problem was reported on.. so I spot checked some....Checked the following Ipads in Browser Stack- for Prod- iPad 7th ; iPad 6th ;  iPad Air 2019 ; iPad Mini 2019 ; iPad Mini 4  and I was not able to reproduce the issue.  Closing bug 

![image](https://user-images.githubusercontent.com/57115301/95873004-16178500-0d35-11eb-85d0-fd4c9d4c3728.png)
![image](https://user-images.githubusercontent.com/57115301/95873032-1f085680-0d35-11eb-9d76-28c56d70e0c6.png)
![image](https://user-images.githubusercontent.com/57115301/95873080-2cbddc00-0d35-11eb-85d4-2ca33e498fd7.png)
![image](https://user-images.githubusercontent.com/57115301/95873109-32b3bd00-0d35-11eb-99fa-67263ebc76da.png)
![image](https://user-images.githubusercontent.com/57115301/95873128-38a99e00-0d35-11eb-85bb-6d6aa08418a7.png)

**Closed by monicakarnes** 2020-10-13 14:20 UTC
Labels: Bug (low)
