### ISSUE TITLE
Cons webpage - Parties for current day are moved to the 'past' tab and should not be 

### ISSUE THREAD

**Issue by suehamre** [tastefully-simple/cornerstone#385] opened 2020-10-15 15:34 UTC
### Expected behavior
Parties with party dates of the current day should be listed on the consultants webpage under "attend" not "past". They should not moved to the "past" until the following day. 

### Actual behavior
Current day parties are being moved to the "past" tab on the day of the party. 

### Steps to reproduce behavior
set up party for current day in myHQ. View TS.com and the consultants webpage and 'my parties' section. 
Example in QA1 for today 10/15/20  - CID #28 - 
![image](https://user-images.githubusercontent.com/57115316/96152192-e487f080-0ed1-11eb-839a-044651a3ed61.png)

![image](https://user-images.githubusercontent.com/57115316/96151930-91ae3900-0ed1-11eb-9f11-9ce49dd1c45c.png)
![image](https://user-images.githubusercontent.com/57115316/96151950-98d54700-0ed1-11eb-8a42-e797377e0bad.png)

Info from Zendesk ticket #152677  - PROD Example: 
Received this from Michelle Kalin #5795

Ruth Kennedy -
Party ID #: P11334294

And, another issue that needs to get corrected ASAP. On our webpages, parties are moving from the “current” to “past” party tab even before the party happens! It happened to a host last week (who ended up canceling her catalog/online party because of all of the TS glitches). AND, for my part last night, Ruth’s party switched to “past” yesterday MORNING (party was at 7pm). That host was getting complaints from guests who weren’t able to attend but had intended to order online yesterday afternoon/evening but we’re having trouble finding her party.
Parties should NOT move to the “past” tab until the day AFTER the party!
Michelle Kalin

**Comment by richierubin** [comment] 2020-10-21 19:15
Not a bug, per Sue.

**Comment by suehamre** [comment] 2020-10-21 22:54
Richie - I think you may have misunderstood me, this was a bug, but I see that it is now fixed.

**Comment by suehamre** [comment] 2020-11-05 13:46
Reopening this bug to try to determine why the fix did not make it to production. This is working in QA1, but not prod. 
Example from PROD 
CID#154612 Merrimack NH  - I searched for parties in Pennsylvannia and chose one for todays date, then view her webpage and you can see it is listed under the 'Past tab' 
![image](https://user-images.githubusercontent.com/57115316/98248316-6223a700-1f3a-11eb-95db-69707c6db524.png)
Example from QA1: 
CID#28 - Harper Test 11/5 shows under 'attend' like it should: 
![image](https://user-images.githubusercontent.com/57115316/98248704-e9711a80-1f3a-11eb-951b-959b9e751cfa.png)

**Comment by suehamre** [comment] 2020-11-11 20:03
I was finally able to duplicate this with Jared's brilliant suggestion. :) So, this is breaking on catalog and fundraiser parties we believe because there is no time set for these party types. I have a few examples for today 11/11 under CID #28 in QA1. 
Party ID's in QA1 are: # P10370817 & # P10370819

**Comment by richierubin** [comment] 2020-11-11 23:01
I can change the logic for parties that do not have a valid time to 11:59:59PM instead of 12:00:00 as they are currently.

**Comment by monicakarnes** [comment] 2020-11-17 22:44
catalog parties 
![image](https://user-images.githubusercontent.com/57115301/99459307-7fba1e80-28f3-11eb-95ca-47a9762e1a50.png)
![image](https://user-images.githubusercontent.com/57115301/99459345-91032b00-28f3-11eb-9512-8df82bc134c6.png)
Fundraiser parties
![image](https://user-images.githubusercontent.com/57115301/99459420-abd59f80-28f3-11eb-8a5e-5446205e66a4.png)
![image](https://user-images.githubusercontent.com/57115301/99459445-b5f79e00-28f3-11eb-87c2-335504ddaec7.png)
Open house
![image](https://user-images.githubusercontent.com/57115301/99459615-ff47ed80-28f3-11eb-986e-1e362ae304f6.png)
![image](https://user-images.githubusercontent.com/57115301/99459625-053dce80-28f4-11eb-97be-f20721adfece.png)

closing

**Closed by monicakarnes** 2020-11-17 22:44 UTC
Labels: Bug (hot)
